### ISSUE TITLE
[Bug]-userProfile 모달 버그 픽스

### ISSUE THREAD

**Issue by Hajin-Bang** [FRONTENDSCHOOL7/final-10-GameBuddy#132]
# Description
userProfile 모달 버그 픽스

# Todo
- [ ] 게시글 삭제 시 상세 모달 내리기
- [ ] confirm창 아니오 선택 시 모달 초기화
- [ ] myPostList, MoreModal 모달 변수 정리
- [ ] 등등

# ETC
#128
