### ISSUE TITLE
[Design]- 반응형 구현 및 폰트 적용(추가 진행중)

### ISSUE THREAD

**Issue by Hajin-Bang** [FRONTENDSCHOOL7/final-10-GameBuddy#135]
# Description
디자인 수정 및 폰트 적용

# Todo
- [x] globalStyle 기본 폰트 설정 (Roboto 400)
- [x] 헤더 푸터 디자인(색상, 간격 등) 수정 
- [x] 헤더 푸터 반응형 구현 
  - 푸터 크기 세가지 (좌측260px, 좌측 72px, 하단)
    - 좌측 72px: 웹페이지에 작은 푸터 넣고싶을 때 써주십쇼
  - 푸터 hover시 애니메이션 적용
- [x] 채팅 페이지 반응형 구현
- [x] 프로필 페이지 반응형 일부 구현 

- [ ] 푸터 전환 시 애니메이션 적용 (부드럽게 전환) 
- [x] 푸터 디자인 수정
- [x] 프로필 페이지 반응형 구현
- [x] 게시글 상세모달 반응형 구현 
- [ ] loadingPage 디자인 수정
- [ ] Splash 디자인 수정
- [ ] 모달 디자인 수정
- [x] SearchPage 반응형 구현
- [ ] search 모달 구현
- [x] 상세 모달 더보기 기능 구현

# ETC
