### ISSUE TITLE
[Feat]-게임 모집 및 참여 기능 구현

### ISSUE THREAD

**Issue by GedFlow** [FRONTENDSCHOOL7/final-10-GameBuddy#155]
# Description
게임 모집글 기능 구현

# Todo
- [x] 마스터계정 생성
- [x] 게임모집글 작성 API json 커스터마이징( 현재 itemName에 게임이름, price에 최대모집인원, link에 모집설명, itemImage에 게임사진 임. itemName에 배열을 넣어 [유저의 계정ID, 게임이름]과 가틍 방식으로 만들고 price에 현재모집인원을 설정한다. price는 숫자형만 받을 수 있어 최대모집인원은 link에 포함한다. link는 [최대모집인원, 모집설명, 참여한 유저들의 계정ID]과 같은 방식으로 작동한다.
- [x] 모집글 수정 API도 위에 맞춰 수정해줘야함.
- [x] 게임이탈버튼 만들기
- [x] 게임참여버튼과 이탈버튼 기능구현
- [x]  유저프로필 수정시 게임모집글 계정명도 같이 수정(ex: 계정명A가 계정명을 B로 바꾸면, A로 등록된 게임모집글의 계정명도 모두 B로 바꿔줌), 

# ETC
