### ISSUE TITLE
[Design]-헤더푸터 디자인 통일

### ISSUE THREAD

**Issue by Hajin-Bang** [FRONTENDSCHOOL7/final-10-GameBuddy#171]
# Description
헤더 푸터 디자인 통일

# Todo
- [ ] pc버전 헤더 디자인 통일
- [x] pc버전 푸터 디자인 통일
- [x] splash -> 로그인 넘어갈 때 user없다고 뜨는 버그 픽스

# ETC
