### ISSUE TITLE
[Design]-디자인 수정 및 버그픽스

### ISSUE THREAD

**Issue by GedFlow** [FRONTENDSCHOOL7/final-10-GameBuddy#184]
# Description
디자인 수정 및 버그픽스

# Todo
- [ ] 팔로우 및 팔로잉 웹화면 UI/UX 고려
- [x] 게임모집글 닫기버튼 line-height
- [x] 모집글 모달창 디자인 수정(프로필이미지와 아티클을 수평배치, 모달창 메인이미지 크기 조절)

# ETC
