### ISSUE TITLE
[Feat]-로그인 기능 구현

### ISSUE THREAD

**Issue by GedFlow** [FRONTENDSCHOOL7/final-10-GameBuddy#24]
# Description
로그인 기능 구현하기

# Todo
- [x] html 틀 짜기 (로그인, 회원가입, 메인페이지)
- [x] api 사용해서 로그인 기능 구현
- [x] 메인페이지 접속 시, 로컬스토리지에 토큰이 없으면 로그인 화면으로 이동하게 구현 (토큰은 로그인 성공시 로컬스토리지에 저장됨)
- [ ] 로그인에 실패했을 때, 로컬스토리지 값 초기화해야함. 이미 유효한 토큰이 존재하면 실패해도 메인페이지로 이동하기 때문.

# ETC
.

**Comment by GedFlow** [comment]
@JJamVa

- 로그인 과정에서 필요한 기본 페이지(로그인화면, 회원가입화면, 메인화면) html 틀만 잡았습니다. 
- axios를 사용해 api를 받아와 로그인 기능 구현했습니다.
- 로그인에 성공하면 로컬 스토리지에 토큰값을 저장합니다.
- 메인페이지 접속시 토큰이 없으면 로그인화면으로 자동으로 이동합니다.
- 토큰의 유효성을 검사하는 기능이 필요합니다.
