### ISSUE TITLE
[Feat]-회원가입 기능 구현

### ISSUE THREAD

**Issue by GedFlow** [FRONTENDSCHOOL7/final-10-GameBuddy#41]
# Description
- 회원가입 기능 구현

# Todo
- [x] 1. 이메일, 패스워드 입력 및 검증 컴포넌트 개발
- [x] 2. 그 외 이미지, 사용자 이름, 계정ID, 소개 설정 컴포넌트 개발
- [x] api 활용해서 기능 구현
- [x] SignUpPage에서 두 개의 컴포넌트를 관리(1번 2번). 1번이 성공적으로 끝나면 2번 컴포넌트로 전환되며, 2번까지 끝나면 성공적으로 회원가입이 되고 로그인 화면으로 이동.

# ETC
- #24
