### ISSUE TITLE
[Feat]-탭바(푸터) 기능 구현

### ISSUE THREAD

**Issue by Hajin-Bang** [FRONTENDSCHOOL7/final-10-GameBuddy#43]
# Description
푸터 기능 구현

# Todo
- [ ] 탭바 html 작성하기
- [ ] 홈, 채팅, 게시글 작성, 프로필 각 버튼 이동
- [ ] 버튼 클릭시 활성화되도록 (stroke굵게)

# ETC
.
