### ISSUE TITLE
[Feat]-헤더 기능 구현

### ISSUE THREAD

**Issue by Hajin-Bang** [FRONTENDSCHOOL7/final-10-GameBuddy#44]
# Description
헤더 기능 구현

# Todo
- [ ] 메인피드 헤더 (로고, 검색) 
- [ ] 그 외 헤더 (뒤로가기, 더보기)
- [ ] 더보기별로 항목 다르게 ......

# ETC
..........
