### ISSUE TITLE
[Design] - 회원가입 화면 개발

### ISSUE THREAD

**Issue by GedFlow** [FRONTENDSCHOOL7/final-10-GameBuddy#60]
# Description
회원가입 화면( + 프로필 등록 화면) 개발

# Todo
- [x] 회원가입 화면(이메일, 패스워드 입력화면) 개발
- [x] 회원가입 화면(개인 프로필 입력화면) 개발
- [x] 회원가입 프로필 설정 화면에서 프사 변경 기능 구현

# ETC

**Comment by GedFlow** [comment]
# Todo 새로운 이슈
- [ ] 회원가입 할 때, accountName 중복검사 하고 예외처리 해야함.
- [ ] 이미지 압축할 필요 있음(링크를 줄이고, 이미지 파일 크기와 해상도도 줄여야함)
