### ISSUE TITLE
[Bug]-Footer active 에러 해결

### ISSUE THREAD

**Issue by Hajin-Bang** [FRONTENDSCHOOL7/final-10-GameBuddy#63]
# Description
Footer active 에러 해결 및 관련 Router 분리

# Todo
- [x] active 사용 시 콘솔 창 에러나는 버그 수정
- [x] footer 확인에 필요한 Router 분리 
- [x] navigate 주석 해제

# ETC
1. active 속성이 styled components에만 적용되도록 active => $active로 변경 (Dom까지 전달되면 경고 발생)
2. 라우터 추가 페이지: ChattingList, Write, Profile
