### ISSUE TITLE
[Design]-Header,Footer 디자인 수정

### ISSUE THREAD

**Issue by Hajin-Bang** [FRONTENDSCHOOL7/final-10-GameBuddy#65]
# Description
Header, Footer 상하단에 고정하기 위해 디자인 변경

# Todo
- [x] Header 상단에 고정 
- [x] Footer 하단에 고정
- [x] MainFeed 헤더 푸터 영역을 제외하고 움직이도록 디자인 변경

# ETC
#44  #49 
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  z-index: 1000;
  box-sizing: border-box;

#50 
  flex: 1 auto;
  overflow-y: auto;
