### ISSUE TITLE
[Design]- ProfilePage 레이아웃 구현

### ISSUE THREAD

**Issue by Hajin-Bang** [FRONTENDSCHOOL7/final-10-GameBuddy#69]
# Description
Profile Page 레이아웃 구현

# Todo
- [x] Profile Component UI
- [x] Recruit Component UI
- [x] MyPostList Component UI
- [x] UserProfile, MyProfile 구분
- [x] ProfilePage에 구현

# ETC
