### ISSUE TITLE
[Feat]-MainFeed 및 PostDetailModal 기능 구현

### ISSUE THREAD

**Issue by JJamVa** [FRONTENDSCHOOL7/final-10-GameBuddy#75]
# Description
MainFeed 기능 및 PostDetailModal 기능 구현 & 디자인 수정

# Todo
- [ ] MainFeed 기능 구현
- [ ] PostDetailModal 기능 구현

# ETC
- [ ] MainFeed 디자인 수정
- [ ] PostDetailModal 디자인 수정
