### ISSUE TITLE
[Design]-로그인, 회원가입 기능 수정 및 개선

### ISSUE THREAD

**Issue by GedFlow** [FRONTENDSCHOOL7/final-10-GameBuddy#88]
# Description
로그인 및 회원가입 기능 수정 및 개선

# Todo
- [x] 회원가입 화면 뒤로가기 만들기
- [x] 로그인, 회원가입 화면 input값 글씨 크기 작게 만들기
- [x] 회원가입 프로필사진 이미지 좀 더 크게 만들기

# ETC
